repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
        exclude: README.md

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.9.1
    hooks:
      - id: isort
        args: [
                "-m", "VERTICAL_HANGING_INDENT",
                "--profile", "black",
                "--trailing-comma",
      ]

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.4
    hooks:
      - id: flake8
        exclude: ^butler_bot/|^billing/|^common/|^migrations/
        args: [
                "--max-line-length=100",
                "--exclude=*migrations*",
        ]

  - repo: https://github.com/psf/black
    rev: 20.8b1
    hooks:
      - id: black
        language_version: python3
        args: [
                "--line-length=100",
        ]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        args: [
                "--disallow-untyped-defs",
                "--ignore-missing-imports",
                "--exclude=.env|.venv|tests|migrations",
                "--no-warn-no-return",
                ]
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
        args: ['--in-place']

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma

#  - repo: https://github.com/PyCQA/pylint
#    rev: pylint-2.6.0
#    hooks:
#      - id: pylint
