# Generated by Django 3.2.3 on 2021-11-22 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="articleuser",
            options={
                "verbose_name": "Статья пользователя",
                "verbose_name_plural": "Статьи пользователей",
            },
        ),
        migrations.AlterModelOptions(
            name="rss",
            options={"verbose_name": "RSS-фиды", "verbose_name_plural": "RSS-фиды"},
        ),
        migrations.AlterModelOptions(
            name="rssusers",
            options={
                "verbose_name": "RSS-подписки пользователя",
                "verbose_name_plural": "RSS-подписки пользователей",
            },
        ),
    ]
